base_url: https://llm.hpc.rug.nl/
citation_model: openscholar
general_model: llama-3.1-8b-instruct-fp8
server_port: 7863

vector_store: 'data/interim/vs_241218_bge-small-en-v1.5'
embedding_model: 'BAAI/bge-small-en-v1.5'

retriever_top_k: 7