base_url: https://llm.hpc.rug.nl/
citation_model: openscholar
general_model: default-chat
server_port: 7863

vector_store: 'data/processed/vs_250703_bge-small-en-v1.5'
embedding_model: 'BAAI/bge-small-en-v1.5'

retriever_top_k: 7